---
# Variable configuration.
- include: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_distribution_file_variety == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_distribution_file_variety == 'Debian'

- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed) or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed) }}"

# Configure MySQL.
- include: configure.yml
- include: secure-installation.yml
  when: docker_skip_tasks is not defined or not docker_skip_tasks

- include: databases.yml
  when: docker_skip_tasks is not defined or not docker_skip_tasks

- include: users.yml
  when: docker_skip_tasks is not defined or not docker_skip_tasks

- include: replication.yml
  when: docker_skip_tasks is not defined or not docker_skip_tasks
